spring:
  application:
    name: recipebook

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/recipebook}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}

server:
  port: 8080
