name: Push Pipeline

on:
  push:
  pull_request:

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline.yaml
    with:
      run_deploy: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run_healthcheck: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      deploy_ref: ${{ github.sha }}
    secrets: inherit
