name: Push Pipeline

on:
  push:
  pull_request:

jobs:
  ci:
    if: github.event_name == 'pull_request' || github.ref != 'refs/heads/main'
    uses: ./.github/workflows/pipeline.yaml
    with:
      run_deploy: false
      run_healthcheck: false
      deploy_ref: ${{ github.sha }}
    secrets: inherit

  ci_cd:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/pipeline.yaml
    with:
      run_deploy: true
      run_healthcheck: true
      deploy_ref: ${{ github.sha }}
    secrets: inherit
